### PR TITLE
Changed process_rsmas logic flow

### PR DESCRIPTION
**Pull request by Ovec8hkin**
`process_rsmas` now either submits `process_rsmas` as a job file via
`create_batch.submit_script()` or runs the remainder of the routine in
a serial fashion, but not both. This should guarantee that, with the
removal of the `sys.exit()` call from `create_batch`, the main body of
`process_rsmas` is not run twice.

Solves #103 

@2gotgrossman

### CODE REVIEW

**Comment by Ovec8hkin** [comment]
@2gotgrossman This has been tested and works correctly.

**Comment by 2gotgrossman** [comment]
Two comments:
1. Why not remove the `submit_script` call completely and just make the `submit_script` call from `run_operations.py`? @falkamelung any thoughts on this?
2. Move the initiation steps that are currently in `if __name__ == "__main__"` into `main()`

**Review by gravelcycles — CHANGES_REQUESTED** [review]
Two comments:

Why not remove the `submit_script()` call completely and just make the `submit_script()` call from `run_operations.py`? @falkamelung any thoughts on this?
Move the initiation steps that are currently in `if __name__ == "__main__"` into `main()`

**Comment by Ovec8hkin** [comment]
@2gotgrossman Upon further considerations, I think we should leave the `submit_script()` branch as it is, because I definitely see a use case where a user would want to run `process_rsmas` by itself with the submit flag.

**Pull request merged**
