### PR TITLE
Template update options

### PR DESCRIPTION
**Pull request by Ovec8hkin**
Changed `Template().update_options()` to use the `Template().update_option(key, value)` method in lieu of the more complicated double file parsing logic as implemented by @mirzaees.

@mirzaees @falkamelung Would it be helpful to add a method to `Template()` that would write the template options back to a template file?

### CODE REVIEW

**Comment by mirzaees** [comment]
> Changed `Template().update_options()` to use the `Template().update_option(key, value)` method in lieu of the more complicated double file parsing logic as implemented by @mirzaees.
> 
> @mirzaees @falkamelung Would it be helpful to add a method to `Template()` that would write the template options back to a template file?

@Ovec8hkin No I don't think that is required

**Review by mirzaees — CHANGES_REQUESTED** [review]
I think there should be another if to remove options that are commented out (starts with #). We don't want them to be read

**Comment by Ovec8hkin** [comment]
@mirzaees Wouldn't be easier to simply remove that option from `.template` file by hand before updating the `Template()` object? Whats the use case in which you want to comment out a specific line of a `.template` file but not delete the line entirely?

**Comment by mirzaees** [comment]
> @mirzaees Wouldn't be easier to simply remove that option from `.template` file by hand before updating the `Template()` object? Whats the use case in which you want to comment out a specific line of a `.template` file but not delete the line entirely?

@Ovec8hkin yes but not every one knows that commenting will result confusion and they must remove the whole line. I do it sometimes! I think it is better to avoid these things in the code

**Review by mirzaees — APPROVED** [review]

**Pull request merged**
